# fly.toml app configuration file generated for lingering-darkness-2848 on 2023-11-02T02:17:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-darkness-2848"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
