GET https://lingering-darkness-2848.fly.dev/api/persons
###

GET https://lingering-darkness-2848.fly.dev/api/persons/65449bcad9a6cd3f3b55a422
###
GET https://lingering-darkness-2848.fly.dev/api/persons/10
###

GET https://lingering-darkness-2848.fly.dev/info
###

DELETE https://lingering-darkness-2848.fly.dev/api/persons/6544a2cb34143d439c41e184
###
POST https://lingering-darkness-2848.fly.dev/api/persons
Content-TYpe: application/json

{
    "name": "Bob Smith2",
    "number": "123-456-7890"
}
###

PUT https://lingering-darkness-2848.fly.dev/api/persons/6545e741fdebf2046d4c8dd4
Content-TYpe: application/json

{
    "name": "Bob Smith2",
    "number": "123-456-0000"
}