GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons/4
###
GET http://localhost:3001/api/persons/10
###

GET http://localhost:3001/info
###

DELETE http://localhost:3001/api/persons/5
###
POST http://localhost:3001/api/persons
Content-TYpe: application/json

{
    "name": "Bob Smith",
    "number": "123-456-7890"
}

###
###

GET https://lingering-darkness-2848.fly.dev/api/persons
###

GET https://lingering-darkness-2848.fly.dev/api/persons/4
###
GET https://lingering-darkness-2848.fly.dev/api/persons/10
###

GET https://lingering-darkness-2848.fly.dev/info
###

DELETE https://lingering-darkness-2848.fly.dev/api/persons/5
###
POST https://lingering-darkness-2848.fly.dev/api/persons
Content-TYpe: application/json

{
    "name": "Bob Smith",
    "number": "123-456-7890"
}
