GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons/4
###
GET http://localhost:3001/api/persons/10
###

GET http://localhost:3001/info
###

DELETE http://localhost:3001/api/persons/5
###
POST http://localhost:3001/api/persons
Content-TYpe: application/json

{
    "name": "Bob Smith",
    "number": "123-456-7890"
}
###
POST http://localhost:3001/api/persons
Content-TYpe: application/json

{
    "name": "Bo"
}
###
POST http://localhost:3001/api/persons
Content-TYpe: application/json

{
    "name": "Bob Smith",
    "number": "1"
}
###
PUT http://localhost:3001/api/persons/65449c00e35f7a969274c8e9
Content-TYpe: application/json

{
    "name": "Bob Smith",
    "number": "1"
}